#sbatch --err=slurm_chip/cycle_test/voxel.err --out=slurm_chip/cycle_test/voxel.out runpymain.sh cycle_training.py --train_limit 4 --test_limit 4 --gradient_accumulation_steps 2 --epochs 2
#sbatch --err=slurm_chip/cycle_test/voxelfp16.err --out=slurm_chip/cycle_test/voxelfp16.out runpymain.sh cycle_training.py --mixed_precision fp16 --train_limit 4 --test_limit 4 --gradient_accumulation_steps 2 --epochs 2
#sbatch --err=slurm_chip/cycle_test/voxel_disc.err --out=slurm_chip/cycle_test/voxel_disc.out runpymain.sh cycle_training.py --use_discriminator --train_limit 4 --test_limit 4 --gradient_accumulation_steps 2 --epochs 2

sbatch --err=slurm_chip/cycle_test/arrayfp16.err --out=slurm_chip/cycle_test/arrayfp16.out runpymain.sh cycle_training.py --mixed_precision fp16 --fmri_type array --kernel_size 4 --n_layers 4 --sublist 1 --train_limit 100 --test_limit 10 --gradient_accumulation_steps 2 --epochs 5 --val_split 0.25
sbatch --err=slurm_chip/cycle_test/array_disc.err --out=slurm_chip/cycle_test/array_disc.out runpymain.sh cycle_training.py --use_discriminator --fmri_type array --kernel_size 4 --n_layers 4 --sublist 1 --train_limit 100 --test_limit 10 --gradient_accumulation_steps 2 --epochs 5 --val_split 0.25
sbatch --err=slurm_chip/cycle_test/array_disc_unpaired.err --out=slurm_chip/cycle_test/array_disc_unpaired.out runpymain.sh cycle_training.py --use_discriminator --fmri_type array --kernel_size 4 --n_layers 4 --sublist 1 --train_limit 100 --test_limit 10 --gradient_accumulation_steps 2 --epochs 5 --unpaired_image_dataset nouman-10/wikiart_testing --val_split 0.25
sbatch --err=slurm_chip/cycle_test/arrayfp16_translation.err --out=slurm_chip/cycle_test/arrayfp16_translation.out runpymain.sh cycle_training.py --mixed_precision fp16 --fmri_type array --kernel_size 4 --n_layers 4 --sublist 1 --train_limit 100 --test_limit 10 --gradient_accumulation_steps 2 --epochs 5 --val_split 0.25 --translation_loss
sbatch --err=slurm_chip/cycle_test/arrayfp16_reconstruction.err --out=slurm_chip/cycle_test/arrayfp16_reconstruction.out runpymain.sh cycle_training.py --mixed_precision fp16 --fmri_type array --kernel_size 4 --n_layers 4 --sublist 1 --train_limit 100 --test_limit 10 --gradient_accumulation_steps 2 --epochs 5 --val_split 0.25 --reconstruction_loss
sbatch --err=slurm_chip/cycle_test/arrayfp16_reconstruction_translation.err --out=slurm_chip/cycle_test/arrayfp16_reconstruction_translation.out runpymain.sh cycle_training.py --mixed_precision fp16 --fmri_type array --kernel_size 4 --n_layers 4 --sublist 1 --train_limit 100 --test_limit 10 --gradient_accumulation_steps 2 --epochs 5 --val_split 0.25 --reconstruction_loss --translation_loss

sbatch --err=slurm_chip/cycle_test/array_disc_unpaired_translation.err --out=slurm_chip/cycle_test/array_disc_unpaired_translation.out runpymain.sh cycle_training.py --use_discriminator --fmri_type array --kernel_size 4 --n_layers 4 --sublist 1 --train_limit 100 --test_limit 10 --gradient_accumulation_steps 2 --epochs 5 --unpaired_image_dataset nouman-10/wikiart_testing --val_split 0.25 --translation_loss
sbatch --err=slurm_chip/cycle_test/array_disc_unpaired_reconstruction.err --out=slurm_chip/cycle_test/array_disc_unpaired_reconstruction.out runpymain.sh cycle_training.py --use_discriminator --fmri_type array --kernel_size 4 --n_layers 4 --sublist 1 --train_limit 100 --test_limit 10 --gradient_accumulation_steps 2 --epochs 5 --unpaired_image_dataset nouman-10/wikiart_testing --val_split 0.25 --reconstruction_loss
