 sbatch --err=slurm_chip/script_test/cliptext_extract_features_1.err --out=slurm_chip/script_test/cliptext_extract_features_1.out runpymain.sh scripts/cliptext_extract_features.py --sub 1 
 sbatch --err=slurm_chip/script_test/cliptext_regression_1.err --out=slurm_chip/script_test/cliptext_regression_1.out runpymain.sh scripts/cliptext_regression.py --sub 1 
 sbatch --err=slurm_chip/script_test/clipvision_extract_features_1.err --out=slurm_chip/script_test/clipvision_extract_features_1.out runpymain.sh scripts/clipvision_extract_features.py --sub 1 
 sbatch --err=slurm_chip/script_test/clipvision_regression_1.err --out=slurm_chip/script_test/clipvision_regression_1.out runpymain.sh scripts/clipvision_regression.py --sub 1 
 sbatch --err=slurm_chip/script_test/evaluate_reconstruction_1.err --out=slurm_chip/script_test/evaluate_reconstruction_1.out runpymain.sh scripts/evaluate_reconstruction.py --sub 1 
 sbatch --err=slurm_chip/script_test/eval_extract_features_1.err --out=slurm_chip/script_test/eval_extract_features_1.out runpymain.sh scripts/eval_extract_features.py --sub 1 
 sbatch --err=slurm_chip/script_test/roi_extract_1.err --out=slurm_chip/script_test/roi_extract_1.out runpymain.sh scripts/roi_extract.py --sub 1 
 sbatch --err=slurm_chip/script_test/roi_generate_features_1.err --out=slurm_chip/script_test/roi_generate_features_1.out runpymain.sh scripts/roi_generate_features.py --sub 1 
 sbatch --err=slurm_chip/script_test/roi_vdvae_reconstruct_1.err --out=slurm_chip/script_test/roi_vdvae_reconstruct_1.out runpymain.sh scripts/roi_vdvae_reconstruct.py --sub 1 
 sbatch --err=slurm_chip/script_test/roi_versatilediffusion_reconstruct_1.err --out=slurm_chip/script_test/roi_versatilediffusion_reconstruct_1.out runpymain.sh scripts/roi_versatilediffusion_reconstruct.py --sub 1 
 sbatch --err=slurm_chip/script_test/save_test_images_1.err --out=slurm_chip/script_test/save_test_images_1.out runpymain.sh scripts/save_test_images.py --sub 1 
 sbatch --err=slurm_chip/script_test/vdvae_extract_features_1.err --out=slurm_chip/script_test/vdvae_extract_features_1.out runpymain.sh scripts/vdvae_extract_features.py --sub 1 
 sbatch --err=slurm_chip/script_test/vdvae_reconstruct_images_1.err --out=slurm_chip/script_test/vdvae_reconstruct_images_1.out runpymain.sh scripts/vdvae_reconstruct_images.py --sub 1 
 sbatch --err=slurm_chip/script_test/vdvae_regression_1.err --out=slurm_chip/script_test/vdvae_regression_1.out runpymain.sh scripts/vdvae_regression.py --sub 1 
 sbatch --err=slurm_chip/script_test/versatilediffusion_reconstruct_images_1.err --out=slurm_chip/script_test/versatilediffusion_reconstruct_images_1.out runpymain.sh scripts/versatilediffusion_reconstruct_images.py --sub 1 
 sbatch --err=slurm_chip/script_test/cliptext_extract_features_2.err --out=slurm_chip/script_test/cliptext_extract_features_2.out runpymain.sh scripts/cliptext_extract_features.py --sub 2 
 sbatch --err=slurm_chip/script_test/cliptext_regression_2.err --out=slurm_chip/script_test/cliptext_regression_2.out runpymain.sh scripts/cliptext_regression.py --sub 2 
 sbatch --err=slurm_chip/script_test/clipvision_extract_features_2.err --out=slurm_chip/script_test/clipvision_extract_features_2.out runpymain.sh scripts/clipvision_extract_features.py --sub 2 
 sbatch --err=slurm_chip/script_test/clipvision_regression_2.err --out=slurm_chip/script_test/clipvision_regression_2.out runpymain.sh scripts/clipvision_regression.py --sub 2 
 sbatch --err=slurm_chip/script_test/evaluate_reconstruction_2.err --out=slurm_chip/script_test/evaluate_reconstruction_2.out runpymain.sh scripts/evaluate_reconstruction.py --sub 2 
 sbatch --err=slurm_chip/script_test/eval_extract_features_2.err --out=slurm_chip/script_test/eval_extract_features_2.out runpymain.sh scripts/eval_extract_features.py --sub 2 
 sbatch --err=slurm_chip/script_test/roi_extract_2.err --out=slurm_chip/script_test/roi_extract_2.out runpymain.sh scripts/roi_extract.py --sub 2 
 sbatch --err=slurm_chip/script_test/roi_generate_features_2.err --out=slurm_chip/script_test/roi_generate_features_2.out runpymain.sh scripts/roi_generate_features.py --sub 2 
 sbatch --err=slurm_chip/script_test/roi_vdvae_reconstruct_2.err --out=slurm_chip/script_test/roi_vdvae_reconstruct_2.out runpymain.sh scripts/roi_vdvae_reconstruct.py --sub 2 
 sbatch --err=slurm_chip/script_test/roi_versatilediffusion_reconstruct_2.err --out=slurm_chip/script_test/roi_versatilediffusion_reconstruct_2.out runpymain.sh scripts/roi_versatilediffusion_reconstruct.py --sub 2 
 sbatch --err=slurm_chip/script_test/save_test_images_2.err --out=slurm_chip/script_test/save_test_images_2.out runpymain.sh scripts/save_test_images.py --sub 2 
 sbatch --err=slurm_chip/script_test/vdvae_extract_features_2.err --out=slurm_chip/script_test/vdvae_extract_features_2.out runpymain.sh scripts/vdvae_extract_features.py --sub 2 
 sbatch --err=slurm_chip/script_test/vdvae_reconstruct_images_2.err --out=slurm_chip/script_test/vdvae_reconstruct_images_2.out runpymain.sh scripts/vdvae_reconstruct_images.py --sub 2 
 sbatch --err=slurm_chip/script_test/vdvae_regression_2.err --out=slurm_chip/script_test/vdvae_regression_2.out runpymain.sh scripts/vdvae_regression.py --sub 2 
 sbatch --err=slurm_chip/script_test/versatilediffusion_reconstruct_images_2.err --out=slurm_chip/script_test/versatilediffusion_reconstruct_images_2.out runpymain.sh scripts/versatilediffusion_reconstruct_images.py --sub 2 
 sbatch --err=slurm_chip/script_test/cliptext_extract_features_5.err --out=slurm_chip/script_test/cliptext_extract_features_5.out runpymain.sh scripts/cliptext_extract_features.py --sub 5 
 sbatch --err=slurm_chip/script_test/cliptext_regression_5.err --out=slurm_chip/script_test/cliptext_regression_5.out runpymain.sh scripts/cliptext_regression.py --sub 5 
 sbatch --err=slurm_chip/script_test/clipvision_extract_features_5.err --out=slurm_chip/script_test/clipvision_extract_features_5.out runpymain.sh scripts/clipvision_extract_features.py --sub 5 
 sbatch --err=slurm_chip/script_test/clipvision_regression_5.err --out=slurm_chip/script_test/clipvision_regression_5.out runpymain.sh scripts/clipvision_regression.py --sub 5 
 sbatch --err=slurm_chip/script_test/evaluate_reconstruction_5.err --out=slurm_chip/script_test/evaluate_reconstruction_5.out runpymain.sh scripts/evaluate_reconstruction.py --sub 5 
 sbatch --err=slurm_chip/script_test/eval_extract_features_5.err --out=slurm_chip/script_test/eval_extract_features_5.out runpymain.sh scripts/eval_extract_features.py --sub 5 
 sbatch --err=slurm_chip/script_test/roi_extract_5.err --out=slurm_chip/script_test/roi_extract_5.out runpymain.sh scripts/roi_extract.py --sub 5 
 sbatch --err=slurm_chip/script_test/roi_generate_features_5.err --out=slurm_chip/script_test/roi_generate_features_5.out runpymain.sh scripts/roi_generate_features.py --sub 5 
 sbatch --err=slurm_chip/script_test/roi_vdvae_reconstruct_5.err --out=slurm_chip/script_test/roi_vdvae_reconstruct_5.out runpymain.sh scripts/roi_vdvae_reconstruct.py --sub 5 
 sbatch --err=slurm_chip/script_test/roi_versatilediffusion_reconstruct_5.err --out=slurm_chip/script_test/roi_versatilediffusion_reconstruct_5.out runpymain.sh scripts/roi_versatilediffusion_reconstruct.py --sub 5 
 sbatch --err=slurm_chip/script_test/save_test_images_5.err --out=slurm_chip/script_test/save_test_images_5.out runpymain.sh scripts/save_test_images.py --sub 5 
 sbatch --err=slurm_chip/script_test/vdvae_extract_features_5.err --out=slurm_chip/script_test/vdvae_extract_features_5.out runpymain.sh scripts/vdvae_extract_features.py --sub 5 
 sbatch --err=slurm_chip/script_test/vdvae_reconstruct_images_5.err --out=slurm_chip/script_test/vdvae_reconstruct_images_5.out runpymain.sh scripts/vdvae_reconstruct_images.py --sub 5 
 sbatch --err=slurm_chip/script_test/vdvae_regression_5.err --out=slurm_chip/script_test/vdvae_regression_5.out runpymain.sh scripts/vdvae_regression.py --sub 5 
 sbatch --err=slurm_chip/script_test/versatilediffusion_reconstruct_images_5.err --out=slurm_chip/script_test/versatilediffusion_reconstruct_images_5.out runpymain.sh scripts/versatilediffusion_reconstruct_images.py --sub 5 
 sbatch --err=slurm_chip/script_test/cliptext_extract_features_7.err --out=slurm_chip/script_test/cliptext_extract_features_7.out runpymain.sh scripts/cliptext_extract_features.py --sub 7 
 sbatch --err=slurm_chip/script_test/cliptext_regression_7.err --out=slurm_chip/script_test/cliptext_regression_7.out runpymain.sh scripts/cliptext_regression.py --sub 7 
 sbatch --err=slurm_chip/script_test/clipvision_extract_features_7.err --out=slurm_chip/script_test/clipvision_extract_features_7.out runpymain.sh scripts/clipvision_extract_features.py --sub 7 
 sbatch --err=slurm_chip/script_test/clipvision_regression_7.err --out=slurm_chip/script_test/clipvision_regression_7.out runpymain.sh scripts/clipvision_regression.py --sub 7 
 sbatch --err=slurm_chip/script_test/evaluate_reconstruction_7.err --out=slurm_chip/script_test/evaluate_reconstruction_7.out runpymain.sh scripts/evaluate_reconstruction.py --sub 7 
 sbatch --err=slurm_chip/script_test/eval_extract_features_7.err --out=slurm_chip/script_test/eval_extract_features_7.out runpymain.sh scripts/eval_extract_features.py --sub 7 
 sbatch --err=slurm_chip/script_test/roi_extract_7.err --out=slurm_chip/script_test/roi_extract_7.out runpymain.sh scripts/roi_extract.py --sub 7 
 sbatch --err=slurm_chip/script_test/roi_generate_features_7.err --out=slurm_chip/script_test/roi_generate_features_7.out runpymain.sh scripts/roi_generate_features.py --sub 7 
 sbatch --err=slurm_chip/script_test/roi_vdvae_reconstruct_7.err --out=slurm_chip/script_test/roi_vdvae_reconstruct_7.out runpymain.sh scripts/roi_vdvae_reconstruct.py --sub 7 
 sbatch --err=slurm_chip/script_test/roi_versatilediffusion_reconstruct_7.err --out=slurm_chip/script_test/roi_versatilediffusion_reconstruct_7.out runpymain.sh scripts/roi_versatilediffusion_reconstruct.py --sub 7 
 sbatch --err=slurm_chip/script_test/save_test_images_7.err --out=slurm_chip/script_test/save_test_images_7.out runpymain.sh scripts/save_test_images.py --sub 7 
 sbatch --err=slurm_chip/script_test/vdvae_extract_features_7.err --out=slurm_chip/script_test/vdvae_extract_features_7.out runpymain.sh scripts/vdvae_extract_features.py --sub 7 
 sbatch --err=slurm_chip/script_test/vdvae_reconstruct_images_7.err --out=slurm_chip/script_test/vdvae_reconstruct_images_7.out runpymain.sh scripts/vdvae_reconstruct_images.py --sub 7 
 sbatch --err=slurm_chip/script_test/vdvae_regression_7.err --out=slurm_chip/script_test/vdvae_regression_7.out runpymain.sh scripts/vdvae_regression.py --sub 7 
 sbatch --err=slurm_chip/script_test/versatilediffusion_reconstruct_images_7.err --out=slurm_chip/script_test/versatilediffusion_reconstruct_images_7.out runpymain.sh scripts/versatilediffusion_reconstruct_images.py --sub 7 
